# Schema for the configuration of the SVG Icons module.

svg_icons.settings:
  type: config_object
  label: 'SVG Icons settings'
  mapping:
    path:
      type: string
      label: 'Relative path to SVG icons'
    remove_existing_class:
      type: boolean
      label: 'Remove existing class on SVG file'
    default_class:
      type: string
      label: 'Default class to add when creating SVG output'
media.source.svg:
  type: media.source.field_aware
  label: '"SVG" media source configuration'
